### ISSUE TITLE
Automatically generated bibliography?

### ISSUE THREAD

**Issue by briochemc** [kellertuer/kellertuer.github.io#1]
👋 Hi there,

First let me commend you on the best Franklin-based academic website I've seen. I think it should be added to the list on Franklin's ReadMe (cc @tlienart)!

I have a question regarding your bibliography. Did you write those yaml entries by hand or do you have some tool to create them from a `.bib` file?

(And second question: Is it OK to borrow your code to make my own website?)

**Comment by kellertuer** [comment]
Thank you very much for the kind words.

Originally, the Bibliography / Literature was `biblatex` based, but I then wanted to also store information like the image on the side. So I even endet up _designing_ the yaml myself, since some of the entries have special fields (like the image). So – no, that is not done automatically.

I never felt the need for an automatic way either, since I do not write so many papers as that this small step (taking 5 minutes to write the YAML) would be a burden. So I never felt the need to write a bibtex->yaml converter into my own yaml format. Most are identical with the bib latex fields, sure, so it should not be too hard to do.

Feel free to get inspired by my code, for sure!
